cloud:
  aws:
    credentials:
      accessKey: yourAccessKey
      secretKey: yourSecretKey
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: pind.auth@gmail.com
    password: qhdks123!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true